# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
mcVer=26.2
fabricLoader=0.19.3
fabricVersion=0.158.0+26.2
kotlinLoader=1.13.13+kotlin.2.4.10
# Mod Properties
mod_version=1.6.2
maven_group=net.chariskar
archives_base_name=breakthemod
# Dependencies
# check this on https://modmuss50.me/fabric.html
placeholderVersion=3.1.0-beta.1+26.2
clothVersion=21.11.153
modmenu=15.0.2
ktSere=1.6.3
breakTheLibrary=1.6.5
org.gradle.parallel=true
org.gradle.caching=true
