[versions]
kotlin = "2.4.10"
serialization = "1.10.2"
fabric-loom = "1.16-SNAPSHOT"
gradleup-shadow = "9.4.3"

fabric-loader = "0.19.3"
fabric-version = "0.154.0+26.2"
fabric-kotlin = "1.13.12+kotlin.2.4.0"
placeholder-version = "3.1.0-beta.1+26.2"
cloth-version = "26.2.155"
modmenu = "20.0.0-beta.4"
break-the-library = "1.6.16"
r8 = "9.4.18"
mc-ver = "26.2"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gradleup-shadow = { id = "com.gradleup.shadow", version.ref = "gradleup-shadow" }
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "mc-ver" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-version" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
placeholder-api = { module = "eu.pb4:placeholder-api", version.ref = "placeholder-version" }
cloth-config = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth-version" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
breakthelibrary = { module = "com.github.breakthebot:BreakTheLibrary", version.ref = "break-the-library" }
r8 = { module = "com.android.tools:r8", version.ref = "r8" }