modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "breakthemodrewrite"
version = "${version}"
displayName = "breakthemodRewrite"
authors = "charisk"
description = '''

'''
#logoFile = ""

[[dependencies.breakthemodrewrite]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.breakthemodrewrite]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.breakthemodrewrite]]
modId = "architectury"
type = "required"
versionRange = "[15.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "breakthemodrewrite.mixins.json"
